### ISSUE TITLE
will you share the train code?

### ISSUE THREAD

**Issue by xiaoshuguo750** [avoroshilov/tf-squeezenet#1]
Hi！
will you share the train code?
Thanks！

**Comment by avoroshilov** [comment]
Hello!
Sorry, long time passed since I was experimenting with SqueezeNet, but I vaguely remember that the training was based on the https://github.com/rcmalli/keras-squeezenet - you can check it out and see how the training is done there.

**Comment by avoroshilov** [comment]
Hopefully the link helped, closing the issue; could be reopened if further questions will arise.
