### ISSUE TITLE
the pretrained model

### ISSUE THREAD

**Issue by wanjinchang** [avoroshilov/tf-squeezenet#2]
Dear author:
   I cannot find the squeezenet pretrained model of tf for your guideCould you tell where to find??
Thank you very much..

**Comment by avoroshilov** [comment]
Hello!

The weights are being loaded at this line:
https://github.com/avoroshilov/tf-squeezenet/blob/master/squeezenet_tf.py#L202
so the pretrained weights are available as this file:
https://github.com/avoroshilov/tf-squeezenet/blob/master/sqz_full.mat

If you're referring to the headless weights (no classifier), it should be available from the different repo (my style transfer experiments repo):
https://github.com/avoroshilov/neural-style/blob/dev/sqz_notop.mat

Does that help?

**Comment by wanjinchang** [comment]
It does really help!!  Thank you very much!!!

**Comment by avoroshilov** [comment]
Glad it helped! Closing the issue
